project:
  type: website
  output-dir: docs
  
bibliography: literatur.bib
csl: apa.csl

resources:
  - articles/*.pdf

website:
  favicon: "images/tilia_alfredica.ico"
  title: "TILIA ALFREDICA"
  navbar:
    logo: "images/tilia_alfredica_circle.png"
    logo-href: "https://tilia-alfredica.github.io/tilia-alfredica/index.html"
    target: _blank
    right:
      - text: Res Novae
        href: res-novae.qmd
      - text: Res Gestae
        href: res-gestae.qmd
      - text: Correlationes Fallaces
        href: correlationes-fallaces.qmd
      - text: De Tyranno Tironum Scientia
        href: de-tyranno.qmd


format:
  html:
    allow-html: true
    lang: de
    css: tilia-alfredica.css

editor: visual

